### ISSUE TITLE
Puzzle 1:  SOCIALLY DISTANCED  [6 points]

### ISSUE THREAD

**Issue by tjperr** [tjperr/rss-quiz-2020#1]
The mayor of Alphaville has just announced a new restriction on all festive text, to ensure that the letters of the alphabet remain socially distanced – with the card below providing an illustration of the new rule in action. (Click on the image to enlarge it. You can do this for any of the images in the quiz.)

Can you figure out what’s been done to the text, and what the message says?

If you apply the same rule to the (assumed) name of the person who brought these lines to prominence, 65 years ago, what two letters appear in the result?

(Hint: These two letters appear consecutively on the penultimate line of the card, in lower case.)

![](https://www.rss.org.uk/RSS/media/News-and-publications/News/christmasquiz2020/P1_1800_V1.png)

**Comment by johnmatthewswift** [comment]
The words are the first verse of 1955 UK Christmas No. 1 - "Christmas Alphabet" by "Dickie Valentine".
The rule is to remove all letters from the question title "Socially Distanced" from that verse.
Applying the same rule to "Dickie Valentine" leaves "kv", which do appear consecutively on the penultimate line.
