### ISSUE TITLE
 Puzzle 12:  153 CIPHER  [6 points]

### ISSUE THREAD

**Issue by tjperr** [tjperr/rss-quiz-2020#12]
![](https://www.rss.org.uk/RSS/media/News-and-publications/News/christmasquiz2020/P12_1800_V1.png)

(Note: The solution to this puzzle may provide a clue to Puzzle 5.)

**Comment by tjperr** [comment]
Resembles the zodiac cypher that was [recently cracked](https://www.sciencealert.com/team-of-amateur-code-breakers-just-solved-51-year-old-zodiac-killer-cipher)

**Comment by mjtriggs** [comment]
From the article: 

> The 340 cipher is read diagonally, starting from the upper-left corner and shifting one box down and two boxes to the right.

**Comment by johnmatthewswift** [comment]
I think the text reads (top line and main block respectively):
```
H I N T - A - H O R S E - O N - A - R I N G - T H A T - S O U N D S - L I K E - A - B U L L

A S T R O L O G Y - I S - L I K E - A - G A M E - O F - C H E S S - 
W I T H - A N - I N V I S I B L E - P A R T N E R - 
W E - S E T - O U T - T H E - B O A R D - A N D - T H E - R U L E S - 
M A K E - A - M O V E - A N D - T H E N - 
F I N D - T H A T - T H E - P I E C E S - A R E - M O V I N G - T H E M S E L V E S - 
A S - I F - B Y - A N - I N V I S I B L E - H A N D - 
N T Y L
```

The last `N T Y L` may be filler, or may be another clue. There are no hyphens or line breaks in the translation, I've added them for ease of reading. 

Some of this text may provide a clue to #5 according to the question.

N.B. It's a straight one-to-one substitution cipher read in the same way as the zodiac cipher in the main text block (i.e. one across two down starting at the start of the same line when you fall off the right hand edge).

**Comment by hjhackett** [comment]
Sounds like a bull: rattle? (cattle)

**Comment by mjtriggs** [comment]
`N T Y L` is the author of the quote - https://en.wikipedia.org/wiki/Noel_Jan_Tyl.

I'd suggest `NOEL` is the hint for #5  - in this case, am I right in thinking Mr Blobby featured on Noel's House Party?

**Comment by johnmatthewswift** [comment]
With N Tyl closed out, that ties up the loose end, and I'd say this one is fully solved.
