### ISSUE TITLE
Puzzle 3:  SWBPWCA = {C, C, R, C, H, M, P, G, A, P, B, T, G, C, C, A, P}  [12 points]

### ISSUE THREAD

**Issue by tjperr** [tjperr/rss-quiz-2020#3]
The 11x11 grid below contains the 17 items of the set referenced in the title, written in lower case. Each highlighted cell (marked with “?”) contains a single unknown letter, and each of the 121 cells is used exactly once.

Can you identify the items, and the set?

(Hint: The letters in the grid do not need to be altered or transformed.)

What name is revealed by the seven highlighted cells, and how is it connected to two of the items?

Explain how a closely related item (from a slightly larger set) may be created through a one-character transformation of the highlighted name.

![](https://www.rss.org.uk/RSS/media/News-and-publications/News/christmasquiz2020/P3_1200_V1.png)

**Comment by hjhackett** [comment]
Looks like maybe some Christmas words jumbled up but connected?

e.g. carol (blue), christmas (red), advent calendar (green)
![InkedRSSQuiz3](https://user-images.githubusercontent.com/76471988/102875615-ef17b680-443b-11eb-886b-715342dc0eb8.jpg)

**Comment by sajohnston** [comment]
It says each cell is used only once, so I don't think we can have different words using the same cell

**Comment by sajohnston** [comment]
Perhaps, though, we don't need to actually make them close together? We presumably know the first letter of each of the items based on the title (though, that could be wrong), and we know all but seven of the letters, so we could find 17 related items based on that.

**Comment by sajohnston** [comment]
Vowels
a = 26 (2 of which listed in the title set)
e = 7 
i = 5
o = 6
u = 1
y = 1 (could be used as a consonant)

Consonants
b = 3 (1 of which in title)
c = 11 (5 of which in title)
d = 4
g = 4 (2 of which in title)
h = 5 (1 of which in title)
l = 4
m = 4 (1 of which in title)
n = 6
p = 3 (all in title)
r = 9 (1 of which in title)
s = 4
t = 10 (1 of which in title)
v = 1

Of the 7 mystery letters, we can presume at least one is a vowel, but probably more than one (Schmidt is a seven-letter name with only one vowel for example).

**Comment by kellettdan** [comment]
This looks to be to do with Best Picture winners with single word titles (for example I have found Amadeus, Crash, Argo, Patton, Chicago, Parasite). I will keep working on this

**Comment by kellettdan** [comment]
Single Word Best Picture Winners C???? A????

**Comment by mjtriggs** [comment]
@bobbins3000 - Are these found moving in any direction or like in a traditional wordsearch?

**Comment by kellettdan** [comment]
Cimarron (in beige)
Cavalcade (in green)
Rebecca (in apricot)
Casablanca (in grey)
Hamlet (in beige)
Marty (in grey)
Patton (in apricot)
Gandhi (in green)
Amadeus (in yellow)
Platoon
Braveheart
Titanic (in blue)
Gladiator (in red)
Chicago (in blue)
Crash (in blue)
Argo (in beige)
Parasite (in purple)

**Comment by kellettdan** [comment]
![rss](https://user-images.githubusercontent.com/9040553/102905853-aa0b7880-446b-11eb-8729-4c8bd6f70e79.PNG)

**Comment by kellettdan** [comment]
OLIVIER - starred in both Rebecca and Hamlet

**Comment by kellettdan** [comment]
Also - turn 'i' upside down and re-arrange to get Oliver! (also a one-word best picture winner)

**Comment by kellettdan** [comment]
Still don't know what the 'CA' stands for

**Comment by kellettdan** [comment]
May be to do with why Moonlight, Spotlight & Unforgiven are not in this set - hmm

**Comment by kellettdan** [comment]
Got it - 'Containing A'

**Comment by sajohnston** [comment]
It seems like we can close this?
