### ISSUE TITLE
Puzzle 7:  LGRTJ!  [14 points]

### ISSUE THREAD

**Issue by tjperr** [tjperr/rss-quiz-2020#7]
In each of the 14 clues below, one of the words is wrong – in fact, it belongs to a different clue! Can you figure out how everything’s been jumbled up, and solve the clues?

Your 14 answers should fall naturally into two groups. What partnership is evoked by these groups? Can you locate a hidden reference in the corrected clues to one of their previous endeavours (which, sadly, isn’t quite as festive as the name might suggest)?
 

- UPCOMING HORROR FILM BASED ON “THE QUIET TIN”

- OPPOSITE OF USEFUL

- SCOTTISH WOODS WHERE ROBERT WOODROW CLAIMED TO SEE A U.F.O.

- BAND BEHIND “PERSISTENCE OF CONSCIENCE”

- SECOND WORD IN THE TITLE OF THE 2018 ALBUM BY TIME

- COASTAL CITY LOCATED 230 KM EAST-NORTH-EAST OF ALEXANDRIA

- BIRTH MONTH OF OWEN WILSON

- ARCHITECT WHO HELPED HADRIAN RECONSTRUCT EVERGREEN

- WORLD SERPENT IN BALINESE MYTHOLOGY, WHO CREATED A BOY

- CITY IN WHICH HENDRIK TAYLOR WAS BORN

- OBJECT LIFTED BY DANNY MORGAN USING BALLOONS FILLED WITH EELS

- THIRD WORD OF “THE OLD LIE”, AS DESCRIBED BY WILFRED RHODES

- CONTINENT IN WHICH TURTLE ISLAND IS LOCATED

- FIRST ELEMENT AFTER HELIUM IN THE PERIODIC TABLE

**Comment by sajohnston** [comment]
Scottish Woods where Robert **Taylor** claimed to see a UFO.  = Dechmont Woods

I think 'Woodrow' could belong where 'Owen' is in Birth Month of Owen Wilson, in which case the answer is December.

**Comment by sajohnston** [comment]
OBJECT LIFTED BY DANNY MORGAN USING BALLOONS FILLED WITH **HELIUM** - Deckchair

FIRST ELEMENT AFTER **TIN** IN THE PERIODIC TABLE - Antimony

**Comment by sajohnston** [comment]
WORLD SERPENT IN BALINESE MYTHOLOGY, WHO CREATED A **TURTLE** - Antaboga

**Comment by tjperr** [comment]
Looks like the answer grouping could be words starting with A and D

**Comment by sajohnston** [comment]
The partnership is Ant & Dec, but I don't know what the not-as-festive-as-it-sounds endeavor is.

**Comment by sajohnston** [comment]
THIRD WORD OF “THE OLD LIE”, AS DESCRIBED BY WILFRED **OWEN** - Decorum

**Comment by sajohnston** [comment]
COASTAL CITY LOCATED 230 KM EAST-NORTH-EAST OF **RHODES** - Antalya

UPCOMING HORROR FILM BASED ON “THE QUIET **BOY**” - Antlers

BAND BEHIND “PERSISTENCE OF **TIME**” - Anthrax

OPPOSITE OF **EVERGREEN** - Deciduous

CONTINENT IN WHICH **USEFUL** ISLAND IS LOCATED - Antarctica

SECOND WORD IN THE TITLE OF THE 2018 ALBUM BY **EELS** - Deconstruction

CITY IN WHICH HENDRIK **CONSCIENCE** WAS BORN - Antwerp

ARCHITECT WHO HELPED HADRIAN RECONSTRUCT **ALEXANDRIA** - Decriannus

**Comment by mjtriggs** [comment]
Have we got all the clues now?

**Comment by sajohnston** [comment]
Yeah, we just need the hidden Ant and Dec reference

**Comment by sajohnston** [comment]
The initials of the switched words spell “Better Watch Out” which I guess is one of their songs, and is also the lyric to a Christmas song.

**Comment by kellettdan** [comment]
LGRTJ! the clue's title stands for 'Let's Get Ready To Jumble!' - a play of the Ant & Dec hit where Rhumble has been replaced by Jumble
